name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Выберите версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python test.py  # Ваш скрипт или команда для тестирования

    - name: Send message to GitHub Conservation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        MESSAGE="Новый коммит! Тесты успешно пройдены."
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -d "{ \"body\": \"$MESSAGE\" }" \
        "https://api.github.com/repos/${GITHUB_REPOSITORY}/discussions/${{ github.event.repository.id }}/comments"
