name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python test.py  # Запуск тестов

    - name: Send message to Discussions
      if: success()
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.graphql(mutation {
            addDiscussionComment(input: { discussionId: "DISCUSSION_ID", body: "Новый комментарий после успешных тестов." }) {
              comment {
                id
              }
            }
          });
